/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedEntryRouteImport } from './routes/_authenticated/entry'

const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/_authenticated/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEntryRoute = AuthenticatedEntryRouteImport.update({
  id: '/_authenticated/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/entry': typeof AuthenticatedEntryRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/entry': typeof AuthenticatedEntryRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/entry': typeof AuthenticatedEntryRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/entry' | '/records' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/entry' | '/records' | '/settings'
  id:
    | '__root__'
    | '/_authenticated/entry'
    | '/_authenticated/records'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedEntryRoute: typeof AuthenticatedEntryRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/entry': {
      id: '/_authenticated/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof AuthenticatedEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedEntryRoute: AuthenticatedEntryRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
